version: "3"

services:

  weight-tracker-api:
    build: .
    depends_on:
      - redis
      - postgres
      - database-migration
    ports:
      - 5005:5005
      - 8000:8000
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.coursier:/root/.coursier"
      - ".:/opt/weight-tracker-api"
      - "/opt/weight-tracker-api/target"
      - "/opt/weight-tracker-api/project/target"
      - "/root/.sbt/1.0/plugins"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: gErL7mV9BZADzkd
      DB_URL: "jdbc:postgresql://postgres:5432/weight-tracker"
      DB_USER: weight-tracker
      DB_PASSWORD: pa55w0rd
      SENDGRID_API_KEY: ""

  database-migration:
    build: .
    command: databaseMigration/run
    depends_on:
      - postgres
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.coursier:/root/.coursier"
      - ".:/opt/weight-tracker-api"
      - "/opt/weight-tracker-api/database-migration/target"
      - "/opt/weight-tracker-api/project/target"
      - "/root/.sbt/1.0/plugins"
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/weight-tracker"
      DB_USER: weight-tracker
      DB_PASSWORD: pa55w0rd

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: weight-tracker
      POSTGRES_USER: weight-tracker
      POSTGRES_PASSWORD: pa55w0rd

  redis:
    image: bitnami/redis
    ports:
      - 6378:6379
    environment:
      REDIS_PASSWORD: gErL7mV9BZADzkd
