version: "3"

services:

  weight-tracker-api:
    build: .
    depends_on:
      - redis
      - postgres
      - database-migration
      - kafka-broker
      - schema-registry
    ports:
      - 5005:5005
      - 8000:8000
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.coursier:/root/.coursier"
      - "/root/.sbt/1.0/plugins"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: gErL7mV9BZADzkd
      DB_URL: "jdbc:postgresql://postgres:5432/weight-tracker"
      DB_USER: weight-tracker
      DB_PASSWORD: Fzy46pxRRd92sE2JRyR2
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONSUMER_GROUP_ID: weight-tracker-api
      APPLICATION_MODE: DockerCompose

  database-migration:
    build: .
    command: databaseMigration/run
    depends_on:
      - postgres
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.coursier:/root/.coursier"
      - "/root/.sbt/1.0/plugins"
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/weight-tracker"
      DB_USER: weight-tracker
      DB_PASSWORD: Fzy46pxRRd92sE2JRyR2

  email-service:
    build: .
    command: emailService/run
    depends_on:
      - kafka-broker
      - schema-registry
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.coursier:/root/.coursier"
      - "/root/.sbt/1.0/plugins"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONSUMER_GROUP_ID: email-service

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: weight-tracker
      POSTGRES_USER: weight-tracker
      POSTGRES_PASSWORD: Fzy46pxRRd92sE2JRyR2

  redis:
    image: bitnami/redis
    ports:
      - 6378:6379
    environment:
      REDIS_PASSWORD: gErL7mV9BZADzkd

  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-broker:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092

  schema-registry:
    image: confluentinc/cp-schema-registry
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181

  schema-registry-ui:
    image: landoop/schema-registry-ui
    ports:
      - 8001:8000
    environment:
      SCHEMAREGISTRY_URL: http://schema-registry:8081
      PROXY: "true"

