version: "3"

services:

#  weight-tracker-api:
#    build: .
#    ports:
#      - 5005:5005
#      - 8000:8000
#    volumes:
#      - "~/.sbt:/root/.sbt"
#      - "~/.coursier:/root/.coursier"
#      - ".:/opt/weight-tracker-api"
#      - "/opt/weight-tracker-api/target"
#      - "/opt/weight-tracker-api/project/target"
#      - "/root/.sbt/1.0/plugins"

  weight-tracker-api-prod:
    image: weight-tracker-api
    ports:
      - 8000:8000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_URL: "jdbc:postgresql://postgres:5432/weight-tracker"
      DB_USER: weight-tracker
      DB_PASSWORD: pa55w0rd

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: weight-tracker
      POSTGRES_USER: weight-tracker
      POSTGRES_PASSWORD: pa55w0rd

  redis:
    image: redis
    ports:
      - 6378:6379
