FROM openjdk:8-jdk-slim

ARG git_commit
ARG git_branch
ARG build_timestamp

ENV GIT_COMMIT $git_commit
ENV GIT_BRANCH $git_branch
ENV BUILD_TIMESTAMP $build_timestamp

WORKDIR /opt

ADD target/universal/{{ project_name }}-*.tgz .

RUN mv {{ project_name }}-* {{ project_name }}

CMD [ "/opt/{{ project_name }}/bin/{{ project_name }}" ]
