FROM openjdk:8-jre-slim

ARG git_commit
ARG git_branch
ARG build_timestamp

ENV GIT_COMMIT $git_commit
ENV GIT_BRANCH $git_branch
ENV BUILD_TIMESTAMP $build_timestamp

WORKDIR /opt/{{ project_name }}

ADD target/universal/{{ project_name }}-*.tgz .

CMD [ "/opt/{{ project_name }}/bin/{{ project_name }}" ]
