apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: weight-tracker-{{ git_branch }}
  name: weight-tracker-api-tls-certificate
spec:
  secretName: weight-tracker-api-tls
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ git_branch }}.api.weight-tracker.ruchij.com
