apiVersion: v1
kind: ConfigMap
metadata:
  namespace: weight-tracker-{{ git_branch }}
  name: weight-tracker-api-config-map
data:
{% for key, value in config_values.weight_tracker_api.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}
