---
- import_playbook: variables.yml
- import_playbook: aws.yml
- hosts: localhost
  connection: local

  tasks:
    - name: Build database migration binary
      shell: cd ../ && sbt databaseMigration/clean databaseMigration/universal:packageZipTarball

    - name: Build database migration Docker image
      block:
        - name: Generate Dockerfile
          template:
            src: docker/Dockerfile-prod.j2
            dest: ../database-migration/Dockerfile-prod
          vars:
            project_name: database-migration

        - name: Build database migration Docker image
          shell: |
            docker build \
              -t database-migration:{{ git_commit }} \
              --build-arg git_commit={{ git_commit }} \
              --build-arg git_branch={{ git_branch }} \
              --build-arg build_timestamp={{ ansible_date_time.iso8601 }} \
              -f ../database-migration/Dockerfile-prod ../database-migration

        - name: Remove Dockerfile
          file:
            path: ../database-migration/Dockerfile-prod
            state: absent

    - name: Build Weight Tracker API application binary
      shell: cd ../ && sbt clean universal:packageZipTarball

    - name: Build Weight Tracker API Docker image
      block:
        - name: Generate Dockerfile
          template:
            src: docker/Dockerfile-prod.j2
            dest: ../Dockerfile-prod
          vars:
            project_name: weight-tracker-api

        - name: Build production Docker image
          shell: |
            docker build \
              -t weight-tracker-api:{{ git_commit }} \
              --build-arg git_commit={{ git_commit }} \
              --build-arg git_branch={{ git_branch }} \
              --build-arg build_timestamp={{ ansible_date_time.iso8601 }} \
              -f ../Dockerfile-prod ../

        - name: Remove Dockerfile
          file:
            path: ../Dockerfile-prod
            state: absent

    - name: Login to ECR
      shell: $(aws ecr get-login --no-include-email --region ap-southeast-2)

    - name: Push database migration Docker image to ECR
      shell: |
        docker tag database-migration:{{ git_commit }} {{ database_migration_ecr_url }}:{{ item }}
        docker push {{ database_migration_ecr_url }}:{{ item }}
      with_items:
        - "{{ git_commit }}"
        - "{{ git_branch }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"

    - name: Push Weight Tracker API Docker image to ECR
      shell: |
        docker tag weight-tracker-api:{{ git_commit }} {{ weight_tracker_api_ecr_url }}:{{ item }}
        docker push {{ weight_tracker_api_ecr_url }}:{{ item }}
      with_items:
        - "{{ git_commit }}"
        - "{{ git_branch }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"
