---
- import_playbook: variables.yml
- import_playbook: aws.yml

- hosts: localhost
  connection: local

  tasks:
    - name: Build database migration binary
      shell: cd ../ && sbt migrationApplication/clean migrationApplication/universal:packageZipTarball

    - name: Build migration application Docker image
      block:
        - name: Generate Dockerfile
          template:
            src: docker/Dockerfile-prod.j2
            dest: ../migration-application/Dockerfile-prod
          vars:
            project_name: migration-application

        - name: Build migration application Docker image
          shell: |
            docker build \
              -t migration-application:{{ git_commit }} \
              --build-arg git_commit={{ git_commit }} \
              --build-arg git_branch={{ git_branch }} \
              --build-arg build_timestamp={{ ansible_date_time.iso8601 }} \
              -f ../migration-application/Dockerfile-prod \
              ../migration-application

        - name: Remove Dockerfile
          file:
            path: ../migration-application/Dockerfile-prod
            state: absent

    - name: Build Weight Tracker API application binary
      shell: cd ../ && sbt clean universal:packageZipTarball

    - name: Build Weight Tracker API Docker image
      block:
        - name: Generate Dockerfile
          template:
            src: docker/Dockerfile-prod.j2
            dest: ../Dockerfile-prod
          vars:
            project_name: weight-tracker-api

        - name: Build production Docker image
          shell: |
            docker build \
              -t weight-tracker-api:{{ git_commit }} \
              --build-arg git_commit={{ git_commit }} \
              --build-arg git_branch={{ git_branch }} \
              --build-arg build_timestamp={{ ansible_date_time.iso8601 }} \
              -f ../Dockerfile-prod \
              ../

        - name: Remove Dockerfile
          file:
            path: ../Dockerfile-prod
            state: absent

    - name: Build Email service application binary
      shell: cd ../ && sbt clean emailService/universal:packageZipTarball

    - name: Build Email service Docker image
      block:
        - name: Generate Dockerfile
          template:
            src: docker/Dockerfile-prod.j2
            dest: ../email-service/Dockerfile-prod
          vars:
            project_name: email-service

        - name: Build production Docker image
          shell: |
            docker build \
              -t email-service:{{ git_commit }} \
              --build-arg git_commit={{ git_commit }} \
              --build-arg git_branch={{ git_branch }} \
              --build-arg build_timestamp={{ ansible_date_time.iso8601 }} \
              -f ../email-service/Dockerfile-prod \
              ../email-service

        - name: Remove Dockerfile
          file:
            path: ../email-service/Dockerfile-prod
            state: absent

    - name: Login to ECR
      shell: $(aws ecr get-login --no-include-email --region ap-southeast-2)

    - name: Push database migration Docker image to ECR
      shell: |
        docker tag migration-application:{{ git_commit }} {{ migration_application_ecr_url }}:{{ item }}
        docker push {{ migration_application_ecr_url }}:{{ item }}
      with_items:
        - "{{ git_commit }}"
        - "{{ git_branch }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"

    - name: Push Weight Tracker API Docker image to ECR
      shell: |
        docker tag weight-tracker-api:{{ git_commit }} {{ weight_tracker_api_ecr_url }}:{{ item }}
        docker push {{ weight_tracker_api_ecr_url }}:{{ item }}
      with_items:
        - "{{ git_commit }}"
        - "{{ git_branch }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"

    - name: Push Email service Docker image to ECR
      shell: |
        docker tag email-service:{{ git_commit }} {{ email_service_ecr_url }}:{{ item }}
        docker push {{ email_service_ecr_url }}:{{ item }}
      with_items:
        - "{{ git_commit }}"
        - "{{ git_branch }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"


