---
- hosts: localhost
  connection: local

  tasks:
    - name: Build database migration application binary
      shell: cd ../ && sbt databaseMigration/clean databaseMigration/universal:packageBin

    - name: Build database migration Docker image
      block:
        - name: Generate database migration Dockerfile
          template:
            src: docker/Dockerfile-prod.j2
            dest: ../database-migration/Dockerfile-prod
          vars:
            project_name: database-migration

        - name: Build database migration Docker image
          shell: docker build -t database-migration -f ../database-migration/Dockerfile-prod ../database-migration

        - name: Remove database migration Dockerfile
          file:
            path: ../database-migration/Dockerfile-prod
            state: absent

    - name: Build production application binary
      shell: cd ../ && sbt clean universal:packageBin

    - name: Build application Docker image
      block:
        - name: Generate application Dockerfile
          template:
            src: docker/Dockerfile-prod.j2
            dest: ../Dockerfile-prod
          vars:
            project_name: weight-tracker-api

        - name: Build production Docker image
          command: docker build -t weight-tracker-api -f ../Dockerfile-prod ../

        - name: Remove application Dockerfile
          file:
            path: ../Dockerfile-prod
            state: absent
