---
- import_playbook: variables.yml
- import_playbook: aws.yml
- import_playbook: secrets-and-configs.yml
- hosts: localhost
  connection: local
  vars:
    weight_tracker_api_docker_image: "{{ weight_tracker_api_ecr_url }}:{{ git_commit }}"
    k8s_config: "{{ lookup('aws_ssm', '/weight-tracker/k8s/config') }}"

  tasks:
    - name: Create output directory
      file:
        path: output
        state: directory

    - name: Create K8s config file
      copy:
        dest: output/kubeconfig
        content: "{{ k8s_config }}"

    - name: Render K8s resource files
      template:
        src: "{{ item }}"
        dest: "output/{{ item | basename }}"
      with_fileglob:
        - k8s/*.yaml

    - name: Create Namespace in K8s
      command: kubectl apply -f output/Namespace.yaml --kubeconfig output/kubeconfig

    - name: Create ConfigMap in K8s
      command: kubectl apply -f output/ConfigMap.yaml --kubeconfig output/kubeconfig

    - name: Create Secrets in K8s
      command: kubectl apply -f output/Secret.yaml --kubeconfig output/kubeconfig

    - name: Deploy application to K8s
      command: kubectl apply -f output/ --kubeconfig output/kubeconfig

    - name: Waiting for successful deployment
      command: "kubectl rollout status deployment weight-tracker-api-deployment --kubeconfig output/kubeconfig -n weight-tracker-api-{{ git_branch }}"
