---
- import_playbook: variables.yml
- import_playbook: aws.yml
- import_playbook: secrets-and-configs.yml
- hosts: localhost
  connection: local
  vars:
    weight_tracker_api_docker_image: "{{ weight_tracker_api_ecr_url }}:{{ git_commit }}"
    database_migration_docker_image: "{{ database_migration_ecr_url }}:{{ git_commit }}"
    k8s_config: "{{ lookup('aws_ssm', '/weight-tracker/k8s/config') }}"

  tasks:
    - name: Create output directories
      block:
        - name: Delete existing directory
          file:
            path: output
            state: absent

        - name: Create main output directory
          file:
            path: output
            state: directory

        - name: Create Weight Tracker API output directory
          file:
            path: output/weight-tracker-api
            state: directory

        - name: Create database migration output directory
          file:
            path: output/database-migration
            state: directory

    - name: Create K8s config file
      copy:
        dest: output/kubeconfig
        content: "{{ k8s_config }}"

    - name: Render K8s Namespace resource file
      template:
        src: "{{ item }}"
        dest: "output/{{ item | basename }}"
      with_fileglob:
        - k8s/*.yaml

    - name: Render Weight Tracker API K8s resource files
      template:
        src: "{{ item }}"
        dest: "output/weight-tracker-api/{{ item | basename }}"
      with_fileglob:
        - k8s/weight-tracker-api/*.yaml

    - name: Render database migration K8s resource files
      template:
        src: "{{ item }}"
        dest: "output/database-migration/{{ item | basename }}"
      with_fileglob:
        - k8s/database-migration/*.yaml

    - name: Create Namespace in K8s
      command: kubectl apply -f output/Namespace.yaml --kubeconfig output/kubeconfig

    - name: Run database migration job
      block:
        - name: Create ConfigMap
          command: kubectl apply -f output/database-migration/ConfigMap.yaml --kubeconfig output/kubeconfig

        - name: Create Secrets
          command: kubectl apply -f output/database-migration/Secret.yaml --kubeconfig output/kubeconfig

        - name: Run Job
          command: kubectl apply -f output/database-migration/Job.yaml --kubeconfig output/kubeconfig

        - name: Wait for Job completion
          command: "kubectl wait --for=condition=complete job/database-migration-job-{{ git_commit }} --kubeconfig output/kubeconfig -n weight-tracker-api-{{ git_branch }} --timeout=600s"

    - name: Deploy Weight Tracker API
      block:
        - name: Create ConfigMap
          command: kubectl apply -f output/weight-tracker-api/ConfigMap.yaml --kubeconfig output/kubeconfig

        - name: Create Secrets
          command: kubectl apply -f output/weight-tracker-api/Secret.yaml --kubeconfig output/kubeconfig

        - name: Deploy application
          command: kubectl apply -f output/weight-tracker-api/ --kubeconfig output/kubeconfig

        - name: Wait for successful Deployment
          command: "kubectl rollout status deployment weight-tracker-api-deployment --kubeconfig output/kubeconfig -n weight-tracker-api-{{ git_branch }}"
