---
- import_playbook: variables.yml
- import_playbook: aws.yml
- import_playbook: secrets-and-configs.yml

- hosts: localhost
  connection: local

  vars:
    weight_tracker_api_docker_image: "{{ weight_tracker_api_ecr_url }}:{{ git_commit }}"
    migration_application_docker_image: "{{ migration_application_ecr_url }}:{{ git_commit }}"
    email_service_docker_image: "{{ email_service_ecr_url }}:{{ git_commit }}"
    k8s_config: "{{ lookup('aws_ssm', '/weight-tracker/k8s/config') }}"

  tasks:
    - name: Create output directories
      block:
        - name: Delete existing directory
          file:
            path: output
            state: absent

        - name: Create main output directory
          file:
            path: output
            state: directory

        - name: Create Weight Tracker API output directory
          file:
            path: output/weight-tracker-api
            state: directory

        - name: Create migration application output directory
          file:
            path: output/migration-application
            state: directory

        - name: Create Email service output directory
          file:
            path: output/email-service
            state: directory

    - name: Create K8s config file
      copy:
        dest: output/kubeconfig
        content: "{{ k8s_config }}"

    - name: Render K8s Namespace resource file
      template:
        src: "{{ item }}"
        dest: "output/{{ item | basename }}"
      with_fileglob:
        - k8s/*.yaml

    - name: Render Weight Tracker API K8s resource files
      template:
        src: "{{ item }}"
        dest: "output/weight-tracker-api/{{ item | basename }}"
      with_fileglob:
        - k8s/weight-tracker-api/*.yaml

    - name: Render migration application K8s resource files
      template:
        src: "{{ item }}"
        dest: "output/migration-application/{{ item | basename }}"
      with_fileglob:
        - k8s/migration-application/*.yaml

    - name: Render Email service K8s resource files
      template:
        src: "{{ item }}"
        dest: "output/email-service/{{ item | basename }}"
      with_fileglob:
        - k8s/email-service/*.yaml

    - name: Create Namespace in K8s
      command: kubectl apply -f output/Namespace.yaml --kubeconfig output/kubeconfig

    - name: Run migration application job
      block:
        - name: Create ConfigMap
          command: kubectl apply -f output/migration-application/ConfigMap.yaml --kubeconfig output/kubeconfig

        - name: Create Secrets
          command: kubectl apply -f output/migration-application/Secret.yaml --kubeconfig output/kubeconfig

        - name: Run Job
          command: kubectl apply -f output/migration-application/Job.yaml --kubeconfig output/kubeconfig

        - name: Wait for Job completion
          command: "kubectl wait --for=condition=complete job/migration-application-job-{{ git_commit }} --kubeconfig output/kubeconfig -n weight-tracker-{{ git_branch }} --timeout=600s"

    - name: Deploy Weight Tracker API
      block:
        - name: Create ConfigMap
          command: kubectl apply -f output/weight-tracker-api/ConfigMap.yaml --kubeconfig output/kubeconfig

        - name: Create Secrets
          command: kubectl apply -f output/weight-tracker-api/Secret.yaml --kubeconfig output/kubeconfig

        - name: Deploy application
          command: kubectl apply -f output/weight-tracker-api/ --kubeconfig output/kubeconfig

        - name: Wait for successful Deployment
          command: "kubectl rollout status deployment weight-tracker-api-deployment --kubeconfig output/kubeconfig -n weight-tracker-{{ git_branch }}"

    - name: Deploy Email service
      block:
        - name: Create ConfigMap
          command: kubectl apply -f output/email-service/ConfigMap.yaml --kubeconfig output/kubeconfig

        - name: Create Secrets
          command: kubectl apply -f output/email-service/Secret.yaml --kubeconfig output/kubeconfig

        - name: Deploy application
          command: kubectl apply -f output/email-service/ --kubeconfig output/kubeconfig

        - name: Wait for successful Deployment
          command: "kubectl rollout status deployment email-service-deployment --kubeconfig output/kubeconfig -n weight-tracker-{{ git_branch }}"
