---
- import_playbook: variables.yml
- import_playbook: aws.yml
- import_playbook: secrets-and-configs.yml
- hosts: localhost
  connection: local
  vars:
    weight_tracker_api_docker_image: "{{ weight_tracker_api_ecr_url }}:{{ git_commit }}"
    k8s_config: "{{ lookup('aws_ssm', '/weight-tracker/k8s/config') }}"

  tasks:
    - name: Create output directory
      file:
        path: output
        state: directory

    - name: Create K8s config file
      copy:
        dest: output/config
        content: "{{ k8s_config }}"

    - name: Render K8s resource files
      template:
        src: "{{ item }}"
        dest: "output/{{ item | basename }}"
      with_fileglob:
        - k8s/*.yaml
