---
- import_playbook: variables.yml
- hosts: localhost
  connection: local

  tasks:
    - set_fact:
        secrets:
          weight_tracker_api:
            DB_USER: "{{ lookup('aws_ssm', '/weight-tracker/api/' + git_branch + '/postgres_user') }}"
            DB_PASSWORD: "{{ lookup('aws_ssm', '/weight-tracker/api/' + git_branch + '/postgres_password') }}"
            REDIS_PASSWORD: "{{ lookup('aws_ssm', '/weight-tracker/api/' + git_branch + '/redis_password') }}"
            SENDGRID_API_KEY: "{{ lookup('aws_ssm', '/weight-tracker/api/sendgrid_api_key') }}"
          database_migration:
            DB_USER: "{{ lookup('aws_ssm', '/weight-tracker/api/' + git_branch + '/postgres_user') }}"
            DB_PASSWORD: "{{ lookup('aws_ssm', '/weight-tracker/api/' + git_branch + '/postgres_password') }}"
        config_values:
          weight_tracker_api:
            DB_URL: "jdbc:postgresql://{{ git_branch }}.postgres.weight-tracker.ruchij.com:5432/weight-tracker"
            REDIS_HOST: "{{ git_branch }}.redis.weight-tracker.ruchij.com"
            REDIS_PORT: 6379
            HTTP_PORT: 8000
          database_migration:
            DB_URL: "jdbc:postgresql://{{ git_branch }}.postgres.weight-tracker.ruchij.com:5432/weight-tracker"


