---
- import_playbook: variables.yml

- hosts: localhost
  connection: local

  tasks:
    - set_fact:
        secrets:
          weight_tracker_api:
            DB_USER: "{{ lookup('aws_ssm', '/weight-tracker/api/' + git_branch + '/postgres_user') }}"
            DB_PASSWORD: "{{ lookup('aws_ssm', '/weight-tracker/api/' + git_branch + '/postgres_password') }}"
            REDIS_PASSWORD: "{{ lookup('aws_ssm', '/weight-tracker/api/' + git_branch + '/redis_password') }}"
            KAFKA_USERNAME: "{{ lookup('aws_ssm', '/weight-tracker/kafka/username') }}"
            KAFKA_PASSWORD: "{{ lookup('aws_ssm', '/weight-tracker/kafka/password') }}"
            SCHEMA_REGISTRY_USERNAME: "{{ lookup('aws_ssm', '/weight-tracker/schema-registry/username') }}"
            SCHEMA_REGISTRY_PASSWORD: "{{ lookup('aws_ssm', '/weight-tracker/schema-registry/password') }}"
          database_migration:
            DB_USER: "{{ lookup('aws_ssm', '/weight-tracker/api/' + git_branch + '/postgres_user') }}"
            DB_PASSWORD: "{{ lookup('aws_ssm', '/weight-tracker/api/' + git_branch + '/postgres_password') }}"
          email_service:
            SENDGRID_API_KEY: "{{ lookup('aws_ssm', '/weight-tracker/api/sendgrid_api_key') }}"
            KAFKA_USERNAME: "{{ lookup('aws_ssm', '/weight-tracker/kafka/username') }}"
            KAFKA_PASSWORD: "{{ lookup('aws_ssm', '/weight-tracker/kafka/password') }}"
            SCHEMA_REGISTRY_USERNAME: "{{ lookup('aws_ssm', '/weight-tracker/schema-registry/username') }}"
            SCHEMA_REGISTRY_PASSWORD: "{{ lookup('aws_ssm', '/weight-tracker/schema-registry/password') }}"
        config_values:
          weight_tracker_api:
            DB_URL: "jdbc:postgresql://{{ git_branch }}.postgres.weight-tracker.ruchij.com:5432/weight-tracker"
            REDIS_HOST: "{{ git_branch }}.redis.weight-tracker.ruchij.com"
            REDIS_PORT: 6379
            HTTP_PORT: 8000
            APPLICATION_MODE: Production
          database_migration:
            DB_URL: "jdbc:postgresql://{{ git_branch }}.postgres.weight-tracker.ruchij.com:5432/weight-tracker"
          email_service:
            APPLICATION_MODE: Production



