apiVersion: v1
kind: Secret
metadata:
  namespace: weight-tracker-{{ git_branch }}
  name: email-service-secrets
stringData:
{% for key, value in secrets.email_service.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}
