apiVersion: v1
kind: ConfigMap
metadata:
  namespace: weight-tracker-{{ git_branch }}
  name: migration-application-config-map
data:
{% for key, value in config_values.migration_application.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}
