apiVersion: v1
kind: Secret
metadata:
  namespace: weight-tracker-{{ git_branch }}
  name: migration-application-secrets
stringData:
{% for key, value in secrets.migration_application.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}
