apiVersion: batch/v1
kind: Job
metadata:
  namespace: weight-tracker-{{ git_branch }}
  name: database-migration-job-{{ git_commit }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: database-migration
          image: {{ database_migration_docker_image }}
          envFrom:
            - configMapRef:
                name: database-migration-config-map
            - secretRef:
                name: database-migration-secrets
